#!/usr/bin/env python

import argparse
import os

from pytorch_lightning import LightningDataModule, LightningModule
from pytorch_lightning.utilities.cli import DATAMODULE_REGISTRY, MODEL_REGISTRY

import src.datamodules
import src.models
from src.utils import LitCLI

MODEL_REGISTRY.register_classes(src.models, LightningModule)
DATAMODULE_REGISTRY.register_classes(src.datamodules, LightningDataModule)


def main():
    os.chdir(os.path.dirname(__file__))

    cli = LitCLI(
        parser_kwargs={
            "default_config_files": ["configs/presets/default.yaml"],
            "epilog": f"""
Availabed Models:      {list(MODEL_REGISTRY)}
Availabed Datamodules: {list(DATAMODULE_REGISTRY)}
            """,
            "formatter_class": argparse.RawDescriptionHelpFormatter,
        },
    )


if __name__ == "__main__":
    main()
